name: application_badge
description: Deep links for flutter desktop
version: 0.0.1
author: Andrei Lesnitsky <andrei.lesnitksy@gmail.com>
homepage: https://github.com/lesnitsky/flutter_desktop_plugins/tree/master/application_badge

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ApplicationBadgePlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
