name: connectivity_fde
description: Temporary desktop implmentations of connectivity from flutter/plugins
version: 0.0.1
author: Andrei Lesnitsky <andrei.lesnitksy@gmail.com>
homepage: https://github.com/lesnitsky/connectivity_fde

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ConnectivityPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
