name: deep_links_fde
description: Deep links for flutter desktop
version: 0.0.1
author: Andrei Lesnitsky <andrei.lesnitksy@gmail.com>
homepage: https://github.com/lesnitsky/flutter_desktop_plugins/tree/master/deep_links_fde

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DeepLinksPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
